### ISSUE TITLE
Configuration document unclear. 

### ISSUE THREAD

**Issue by canerdianeh** [estruyf/homebridge-presence-switch-slack#1]
Config document says to add the slack app to the account (does not specify which account), and the slack app store does not have any apps relating to homebridge. Link to actual app would be helpful here.

**Comment by estruyf** [comment]
Sorry for the confusion. Have you tried to click on the "add to Slack" button on the readme? That should redirect you to slack where you can log into the account/environment to which you want to add the app.

**Comment by canerdianeh** [comment]
That redirects into a whole different slack environment.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by estruyf** [comment]
I’ll check it out!

**Comment by estruyf** [comment]
Updated the link of the button. It should now have been fixed. Tested with another tenant.

**Comment by canerdianeh** [comment]
OK, that works, thanks! .. Might be helpful to also indicate that the "Add To Slack" image is the actual button that needs to be clicked - I initially read it as "look for this button in slack somewhere", and was having a hell of a time finding it.

**Comment by kinouzero** [comment]
Hi,
I've try to add your app to my workspace, this is the message I get

<img width="1679" alt="Capture d’écran 2022-07-11 à 14 23 51" src="https://user-images.githubusercontent.com/4740176/178263573-8032562d-e31e-49b5-af92-accc7338844a.png">

Thanks for your help

**Comment by estruyf** [comment]
Thanks @kinouzero! There was an issue with the redirect to the app. I've just fixed the `add to slack` button on the readme which should make it work again.
